[project]
name = "summarizedexperiment"
dynamic = [
    "version",
]
description = "Container to represent data from genomic experiments"
readme = "README.md"
authors = [
    { name = "Jayaram Kancherla", email = "jayaram.kancherla@gmail.com" },
]
requires-python = ">=3.12"
keywords = [
    "bioinformatics",
    "computational biology",
    "genomics",
    "bioconductor",
    "BiocPy",
    "SummarizedExperiment",
    "transcriptomics",
    "single-cell",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Typing :: Typed",
]
dependencies = [
    "biocframe>=0.7.2",
    "biocutils>=0.3.3",
    "genomicranges>=0.8.2",
    "importlib-metadata>=9.0.0 ; python_full_version < '3.8'",
]


[project.license]
file = "LICENSE.txt"


[project.urls]
Homepage = "https://github.com/BiocPy/summarizedexperiment"
Documentation = "https://biocpy.github.io/summarizedexperiment/"
Source = "https://github.com/BiocPy/summarizedexperiment"
"Bug Tracker" = "https://github.com/BiocPy/summarizedexperiment/issues"

[project.optional-dependencies]
optional = [
    "anndata>=0.13.2",
    "delayedarray>=0.6.2",
    "scipy>=1.18.1",
]
testing = [
    "anndata>=0.13.2",
    "delayedarray>=0.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "setuptools>=84.0.0",
]

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.1.0"

[tool.ruff]
line-length = 120
src = [
    "src",
]
exclude = [
    "tests",
    "docs",
]

[tool.ruff.lint]
extend-ignore = [
    "F821",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402",
    "F401",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing"
testpaths = [
    "tests",
]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B110"]
